# Generated by Django 2.2 on 2019-09-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190904_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='in_sales',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contactsource',
            name='potential_profiles',
            field=models.ManyToManyField(blank=True, default=None, to='sales.SkillProfile'),
        ),
    ]
