# Generated by Django 2.2 on 2019-08-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20190802_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='in_sales',
            field=models.BooleanField(default=False),
        ),
    ]
