# Generated by Django 2.2 on 2019-09-04 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20190904_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('approved', 'Подтвержден')], default='wating', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(blank=True, max_length=2500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cv_url',
            field=models.CharField(blank=True, max_length=2500, verbose_name='Ссылка на резюме'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имейл'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lead_quality',
            field=models.IntegerField(default=0, verbose_name='Качество лида'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_main',
            field=models.CharField(max_length=50, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profiles',
            field=models.ManyToManyField(blank=True, default=None, to='sales.SkillProfile', verbose_name='Проф. профили кандидата'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(blank=True, choices=[('м', 'Мужской'), ('ж', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.ContactSource', verbose_name='Источник контакта'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='result',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('звонок', 'Звонок'), ('email', 'Email'), ('sms', 'Sms'), ('messenger', 'Messenger'), ('автопрозвон', 'Автопрозвон')], max_length=2000),
        ),
    ]
