# Generated by Django 2.2 on 2019-09-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190904_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Город проживания'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cv_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на резюме'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='result',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('звонок', 'Звонок'), ('email', 'Email'), ('sms', 'Sms'), ('messenger', 'Messenger'), ('автопрозвон', 'Автопрозвон')], max_length=200),
        ),
    ]
