# Generated by Django 2.2 on 2019-08-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('sales', '0004_auto_20190802_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
