# Generated by Django 2.2 on 2019-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20190904_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsource',
            name='description',
            field=models.CharField(max_length=250, verbose_name='Описание с примерами'),
        ),
        migrations.AlterField(
            model_name='contactsource',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название источника'),
        ),
        migrations.AlterField(
            model_name='contactsource',
            name='potential_profiles',
            field=models.ManyToManyField(blank=True, default=None, to='sales.SkillProfile', verbose_name='Возможные профили'),
        ),
        migrations.AlterField(
            model_name='skillprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название профиля'),
        ),
    ]
