# Generated by Django 2.2 on 2019-09-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20190905_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='last_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='next_contact_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
