# Generated by Django 2.2 on 2019-08-20 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20190814_1121'),
    ]

    operations = [


        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_quality',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='next_contact_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 20, 15, 51, 0, 179619, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_main',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profiles',
            field=models.ManyToManyField(default=None, to='sales.SkillProfile'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='sex',
            field=models.CharField(blank=True, choices=[('м', 'Мужской'), ('ж', 'Женский')], max_length=1),
        ),
    ]
