# Generated by Django 2.2 on 2019-08-21 08:06

import datetime
from django.db import migrations, models
from django.utils.datetime_safe import date


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20190820_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='next_contact_date',
            field=models.DateTimeField(blank=True, auto_now=True),
        ),
    ]
