# Generated by Django 2.2 on 2019-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20190821_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interaction',
            old_name='comment',
            new_name='result',
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
