# Generated by Django 2.2 on 2019-08-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_auto_20190821_1207'),
    ]

    operations = [

        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('звонок', 'Звонок'), ('email', 'Email'), ('sms', 'Sms'), ('messenger', 'Messenger')], max_length=200),
        ),
    ]
