# Generated by Django 2.2 on 2019-08-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20190821_1231'),
    ]

    operations = [

        migrations.AddField(
            model_name='interaction',
            name='contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.Contact'),
            preserve_default=False,
        ),
    ]
