# Generated by Django 2.2 on 2019-09-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20190911_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'get_latest_by': 'id'},
        ),
    ]
