# Generated by Django 2.2 on 2019-08-22 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
        ('sales', '0011_auto_20190821_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contactable',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_lead',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_pair',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Contact')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Interaction')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Vacancy')),
            ],
        ),
    ]
