# Generated by Django 2.2 on 2019-08-22 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0012_auto_20190822_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provision_agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='provision_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_agent',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sale_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
