# Generated by Django 2.2 on 2019-09-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_contact_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='color',
            field=models.CharField(blank=True, choices=[('purple', 'Фиолетовый'), ('pink', 'Розовый'), ('blue', 'Синий'), ('SkyBlue', 'Голубой'), ('green', 'Зеленый'), ('limegreen', 'СветлоЗеленый'), ('yellow', 'Желтый'), ('orange', 'Оранжевый'), ('tomato', 'Томат'), ('red', 'Красный'), ('brown', 'Коричневый')], max_length=20, verbose_name='Цвет'),
        ),
    ]
