# Generated by Django 2.2 on 2019-09-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_auto_20190912_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телеграм'),
        ),
        migrations.AddField(
            model_name='contact',
            name='viber',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вайбер'),
        ),
    ]
