# Generated by Django 2.2 on 2019-09-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_auto_20190912_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Дополнительно'),
        ),
    ]
