# Generated by Django 2.2 on 2019-09-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20190918_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='objection',
            field=models.CharField(blank=True, max_length=100, verbose_name='Причина отказа'),
        ),
    ]
