# Generated by Django 2.2 on 2019-09-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_contact_objection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('звонок', 'Звонок'), ('email', 'Email'), ('sms', 'Sms'), ('messenger', 'Messenger'), ('автопрозвон', 'Автопрозвон')], default='звонок', max_length=200),
        ),
    ]
