# Generated by Django 2.2 on 2019-10-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_auto_20191019_0728'),
        ('sales', '0018_auto_20190918_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_pair',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='proposed_vacancy',
            field=models.ManyToManyField(blank=True, default=None, to='employer.Vacancy', verbose_name='Предложенные вакансии'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lead_quality',
            field=models.IntegerField(choices=[(-2, 'Отказ'), (-1, 'Недозвон'), (0, 'Новый'), (1, 'Интересно'), (2, 'Другая Вакансия'), (3, 'Приоритет'), (4, 'Сделка')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profiles',
            field=models.ManyToManyField(blank=True, default=None, to='sales.SkillProfile', verbose_name='Професии кандидата'),
        ),
    ]
