# Generated by Django 2.2 on 2019-10-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_auto_20191019_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objection', models.CharField(blank=True, max_length=100, verbose_name='Причина отказа')),
                ('strategy', models.CharField(blank=True, max_length=1500, verbose_name='Как работать с отказом')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='objection',
        ),
    ]
