# Generated by Django 2.2 on 2019-10-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20191019_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='objection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sales.Objection', verbose_name='Причина отказа'),
        ),
    ]
