# Generated by Django 2.2 on 2019-10-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_contact_objection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_pair',
            field=models.BooleanField(default=False, verbose_name='Семейная пара'),
        ),
    ]
