# Generated by Django 2.2 on 2019-10-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20191019_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_pair',
            field=models.BooleanField(default=False, null=True, verbose_name='Семейная пара'),
        ),
    ]
