# Generated by Django 2.2 on 2019-10-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_auto_20191019_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone3',
        ),
    ]
