# Generated by Django 2.2 on 2019-10-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_remove_contact_phone3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_pair',
            field=models.BooleanField(default=False, null=True, verbose_name='Пара'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lead_quality',
            field=models.IntegerField(choices=[(-2, 'Отказ'), (-1, 'Недозвон'), (0, 'Новый'), (1, 'Интересно но позже'), (2, 'Другая Вакансия'), (3, 'Приоритет'), (4, 'Сделка')], default=0, verbose_name='Статус'),
        ),
    ]
