# Generated by Django 2.2 on 2019-10-22 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_auto_20191021_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='objection',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='sales.Objection', verbose_name='Причина отказа'),
        ),
    ]
