# Generated by Django 2.2 on 2019-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_auto_20191022_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Анамнез'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(blank=True, choices=[('звонок', 'Звонок'), ('email', 'Email'), ('sms', 'Sms'), ('messenger', 'Messenger'), ('автопрозвон', 'Автопрозвон')], default='звонок', max_length=200),
        ),
    ]
