# Generated by Django 2.2 on 2019-10-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_auto_20191024_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='result',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
