# Generated by Django 2.2 on 2019-10-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_auto_20191027_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead_quality',
            field=models.IntegerField(choices=[(-2, 'Отказ'), (-1, 'Недозвон'), (0, 'Новый'), (101, 'Ящ'), (1, 'Интересно но позже'), (2, 'Другая Вакансия'), (3, 'Приоритет'), (102, 'Принимает Решение'), (103, 'Ожоп'), (4, 'Сделка')], default=0, verbose_name='Статус'),
        ),
    ]
