# Generated by Django 2.2 on 2019-10-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_auto_20191027_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lead_quality',
            field=models.IntegerField(choices=[(-2, 'Отказ'), (-1, 'Недозвон'), (0, 'Новый'), (101, 'ТЕПЛЫЙ НО ОТЛОЖЕННЫЙ ЗВОНОК'), (1, 'Интересно но позже'), (2, 'Другая Вакансия'), (3, 'Приоритет'), (102, 'Принимает Решение'), (103, 'ОЖИДАНИЕ ОПЛАТЫ'), (4, 'Сделка')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ватсап'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(choices=[('звонок', 'звонок'), ('вайбер', 'вайбер'), ('телеграм', 'телеграм'), ('ватсап', 'ватсап'), ('email', 'email'), ('sms', 'sms'), ('автопрозвон', 'автопрозвон')], default='звонок', max_length=200),
        ),
    ]
