# Generated by Django 2.2 on 2019-08-20 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('office_address', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_expense', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('employers_name', models.CharField(blank=True, max_length=20)),
                ('count_workers', models.CharField(blank=True, max_length=20)),
                ('workplace', models.CharField(blank=True, max_length=20)),
                ('employee_start_date', models.CharField(blank=True, max_length=20)),
                ('working_days', models.CharField(blank=True, max_length=20)),
                ('work_schedule', models.CharField(blank=True, max_length=20)),
                ('job_description', models.CharField(blank=True, max_length=20)),
                ('type_of_residence', models.CharField(blank=True, max_length=20)),
                ('type_of_residence_common', models.CharField(blank=True, max_length=20)),
                ('salary_total', models.CharField(blank=True, max_length=20)),
                ('average_salary_after_trial_period', models.CharField(blank=True, max_length=20)),
                ('average_salary_for_year', models.CharField(blank=True, max_length=20)),
                ('recruiting_contribution', models.CharField(blank=True, max_length=20)),
                ('rewards', models.CharField(blank=True, max_length=20)),
                ('career_opportunities', models.CharField(blank=True, max_length=20)),
                ('overtime_hours', models.CharField(blank=True, max_length=20)),
                ('duration_of_trial_period', models.CharField(blank=True, max_length=20)),
                ('general_qualification_requirements', models.CharField(blank=True, max_length=20)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='VacancyNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expense', models.DateField(blank=True, max_length=30)),
                ('sum_of_expense', models.IntegerField(blank=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Expenses')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer')),
                ('languages', models.ManyToManyField(to='employer.Language')),
            ],
        ),
        migrations.CreateModel(
            name='AgentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.ContactPerson')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
