# Generated by Django 2.0.9 on 2019-07-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('contact_person_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('languages', models.CharField(blank=True, choices=[('English', 'English'), ('Czech', 'Czech'), ('Polish', 'Polish')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('office_address', models.CharField(blank=True, max_length=50)),
                ('site', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=20)),
                ('employers_name', models.CharField(blank=True, max_length=20)),
                ('count_workers', models.CharField(blank=True, max_length=20)),
                ('workplace', models.CharField(blank=True, max_length=20)),
                ('employee_start_date', models.CharField(blank=True, max_length=20)),
                ('working_days', models.CharField(blank=True, max_length=20)),
                ('work_schedule', models.CharField(blank=True, max_length=20)),
                ('job_description', models.CharField(blank=True, max_length=20)),
                ('type_of_residence', models.CharField(blank=True, max_length=20)),
                ('type_of_residence_common', models.CharField(blank=True, max_length=20)),
                ('salary_total', models.CharField(blank=True, max_length=20)),
                ('average_salary_after_trial_period', models.CharField(blank=True, max_length=20)),
                ('average_salary_for_year', models.CharField(blank=True, max_length=20)),
                ('recruiting_contribution', models.CharField(blank=True, max_length=20)),
                ('rewards', models.CharField(blank=True, max_length=20)),
                ('career_opportunities', models.CharField(blank=True, max_length=20)),
                ('overtime_hours', models.CharField(blank=True, max_length=20)),
                ('duration_of_trial_period', models.CharField(blank=True, max_length=20)),
                ('general_qualification_requirements', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='contactperson',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer'),
        ),
    ]
