# Generated by Django 2.0.9 on 2019-06-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('employers_name', models.TextField()),
                ('count_workers', models.IntegerField()),
                ('workplace', models.TextField()),
                ('employee_start_date', models.DateField()),
                ('working_days', models.IntegerField()),
                ('work_schedule', models.TextField()),
                ('job_description', models.TextField()),
                ('type_of_residence', models.TextField()),
                ('type_of_residence_common', models.TextField()),
                ('salary_total', models.IntegerField()),
                ('average_salary_after_trial_period', models.IntegerField()),
                ('average_salary_for_year', models.IntegerField()),
                ('recruiting_contribution', models.IntegerField()),
                ('rewards', models.TextField()),
                ('career_opportunities', models.TextField()),
                ('overtime_hours', models.BooleanField()),
                ('duration_of_trial_period', models.DateField()),
                ('general_qualification_requirements', models.TextField()),
            ],
        ),
    ]
