# Generated by Django 2.0.9 on 2019-06-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='average_salary_after_trial_period',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='average_salary_for_year',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='career_opportunities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='count_workers',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duration_of_trial_period',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employee_start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employers_name',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='general_qualification_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='recruiting_contribution',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='rewards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_total',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type_of_residence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='type_of_residence_common',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_days',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='workplace',
            field=models.TextField(blank=True),
        ),
    ]
