# Generated by Django 2.0.9 on 2019-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='contactperson',
            name='languages',
        ),
        migrations.AddField(
            model_name='language',
            name='contact_persons',
            field=models.ManyToManyField(to='employer.ContactPerson'),
        ),
    ]
