# Generated by Django 2.2 on 2019-09-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='city',
            field=models.CharField(blank=True, max_length=200, verbose_name='Город работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='documents',
            field=models.CharField(blank=True, choices=[('visa', 'Виза'), ('ecard', 'Карта'), ('visa_card', 'Виза+Карта')], max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employee_count',
            field=models.CharField(blank=True, max_length=200, verbose_name='Необходимое количество работников'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название работодателя'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='entering_bonus',
            field=models.CharField(blank=True, max_length=500, verbose_name='Бонус при выходе на работу'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='job_description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Описание работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='living_conditions',
            field=models.CharField(blank=True, max_length=800, verbose_name='Условия проживания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='living_price',
            field=models.CharField(blank=True, max_length=200, verbose_name='Стоимость проживания'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='overtime_hours',
            field=models.CharField(blank=True, max_length=500, verbose_name='Максимальное количество рабочих часов'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position_title',
            field=models.CharField(max_length=200, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.CharField(blank=True, max_length=500, verbose_name='Требования к работнику'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=500, verbose_name='Зарплата после испытательного срока'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_after_year',
            field=models.CharField(blank=True, max_length=500, verbose_name='Зарплата через год'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='start_date',
            field=models.DateField(blank=True, max_length=200, verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Активная'), ('hold', 'Приостановленная'), ('archive', 'Архивная')], default='active', max_length=200),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='trial_duration',
            field=models.CharField(blank=True, max_length=500, verbose_name='Длительность испытательного срока'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='trial_salary',
            field=models.CharField(blank=True, max_length=500, verbose_name='Зарплата во время испытательного срока'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='work_schedule',
            field=models.CharField(blank=True, max_length=500, verbose_name='График работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='working_days',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дни работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='year_bonus',
            field=models.CharField(blank=True, max_length=500, verbose_name='Годовой бонус'),
        ),
    ]
