# Generated by Django 2.2 on 2019-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20190904_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='documents',
            field=models.CharField(blank=True, choices=[('Виза 3 мес', 'Виза 3 мес'), ('Виза 1 год', 'Виза 1 год'), ('Рабочая карта', 'Рабочая карта'), ('Виза 3 месяца + Карта', 'Виза 3 месяца + Карта'), ('Виза 1 год + Карта', 'Виза 1 год + Карта')], max_length=200),
        ),
    ]
