# Generated by Django 2.0.9 on 2019-07-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_auto_20190715_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactperson',
            name='languages',
            field=models.ManyToManyField(to='employer.Language'),
        ),
    ]
