# Generated by Django 2.2 on 2019-09-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20190905_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='employer_description',
            field=models.CharField(blank=True, max_length=400, verbose_name='Описание компании работодателя'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='documents',
            field=models.CharField(blank=True, choices=[('Виза 3 мес', 'Виза 3 мес'), ('Виза 1 год', 'Виза 1 год'), ('Рабочая карта', 'Рабочая карта'), ('Виза 3 месяца + Карта', 'Виза 3 месяца + Карта'), ('Виза 1 год + Карта', 'Виза 1 год + Карта')], max_length=200, verbose_name='Документы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Название работодателя'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Активная'), ('hold', 'Приостановленная'), ('archive', 'Архивная')], default='active', max_length=200, verbose_name='Статус'),
        ),
    ]
