# Generated by Django 2.0.9 on 2019-06-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_auto_20190626_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('language_skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('employer', models.CharField(max_length=50)),
                ('languages', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('office_address', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('contact_list', models.CharField(max_length=50)),
                ('employer_type', models.CharField(max_length=50)),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Vacancy')),
            ],
        ),
        migrations.AddField(
            model_name='contactperson',
            name='employer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Employer'),
        ),
        migrations.AddField(
            model_name='contactlanguages',
            name='contact_person_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.ContactPerson'),
        ),
    ]
