# Generated by Django 2.0.9 on 2019-07-15 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_contactperson_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='contact_persons',
        ),
    ]
