# Generated by Django 2.2 on 2019-09-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_auto_20190911_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='price',
            field=models.IntegerField(verbose_name='Стоимость вакансии'),
        ),
    ]
