# Generated by Django 2.2 on 2019-07-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_language_contact_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_expense', models.CharField(blank=True, max_length=100)),
                ('type_of_type_of_expense', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expense', models.DateField(blank=True, max_length=30)),
                ('sum_of_expense', models.IntegerField(blank=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.Expenses')),
            ],
        ),
    ]
