# Generated by Django 2.0.9 on 2019-06-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_auto_20190627_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
