# Generated by Django 2.2 on 2019-07-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_expenses_historyexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='type_of_type_of_expense',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='type_of_expense',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
