# Generated by Django 2.2 on 2019-09-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0005_auto_20190911_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='for_pairs',
            field=models.BooleanField(default=False, verbose_name='Для семейных пар'),
        ),
    ]
