# Generated by Django 2.0.9 on 2019-07-06 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_auto_20190628_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='vacancy',
        ),
    ]
