# Generated by Django 2.2 on 2019-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0006_vacancy_for_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='documents_add',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительно - Документы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='employee_count_add',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительно - Необходимое количество работников'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='for_pairs_add',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительно - Для семейных пар'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='living_price_add',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительно - Стоимость проживания'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='price_add',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительно - Стоимость вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='start_date_add',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительно - Дата старта'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='trial_duration_add',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительно - Длительность испытательного срока'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_schedule_add',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дополнительно - График работы'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='working_days_add',
            field=models.CharField(blank=True, max_length=500, verbose_name='Дополнительно - Дни работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='position_title',
            field=models.CharField(max_length=580, verbose_name='Название вакансии'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Зарплата после испытательного срока'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='trial_duration',
            field=models.CharField(blank=True, max_length=200, verbose_name='Длительность испытательного срока'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='trial_salary',
            field=models.CharField(blank=True, max_length=200, verbose_name='Зарплата во время испытательного срока'),
        ),
    ]
