# Generated by Django 2.0.9 on 2019-07-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_remove_employer_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='slug',
            field=models.SlugField(default=True, max_length=150, unique=True),
        ),
    ]
