# Generated by Django 2.2 on 2019-09-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_auto_20190913_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='for_pairs_add',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительно - Для семейных пар'),
        ),
    ]
