# Generated by Django 2.2 on 2019-07-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_agentnote_employernote_vacancynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentnote',
            name='text2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employernote',
            name='text2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vacancynote',
            name='text2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
