# Generated by Django 2.2 on 2019-09-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0008_auto_20190913_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='position_title',
            field=models.CharField(max_length=180, verbose_name='Название вакансии'),
        ),
    ]
