# Generated by Django 2.2 on 2019-08-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_auto_20190801_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employernote',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employernote',
            name='id',
        ),
        migrations.AddField(
            model_name='employernote',
            name='employer_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
