# Generated by Django 2.0.9 on 2019-07-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0009_auto_20190706_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='slug',
            field=models.SlugField(max_length=150),
        ),
    ]
