# Generated by Django 2.0.9 on 2019-07-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0010_auto_20190706_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='slug',
        ),
    ]
